### ISSUE TITLE
on genBubtubbead_imaging_serenet_20231204.m

### ISSUE THREAD

**Issue by cowboy446** [kimchange/SeReNet#1]
in `genBubtubbead_imaging_serenet_20231204.m`, line 131-134 (and other 2 following codeblocks alike):
```matlab
for indidx = 1:length(ind)
      inds = ind(indidx) + relativeinds;
      volume(inds) = volume(inds) + (  round(20 + rand()*200) + zeros(size(relativeinds))  );
end
```
limitations on `inds` as the index of the array `volume` should be set:
```matlab
for indidx = 1:length(ind)
      inds = ind(indidx) + relativeinds;
      for idx = 1:length(inds)
             if inds(idx) > 0 && inds(idx) <= synthetic.Height * synthetic.Width * synthetic.Depth
                 volume(inds(idx)) = volume(inds(idx)) + (  round(20 + rand()*200));
             end
      end
end
```
because sometimes part of `relativeinds` exceed the boundaries of `ind`, causing illegal index of `volume` from both sides < 0 and > size of `volume`:
```
Array indices must be positive integers or logical values.

Error in genBubtubbead_imaging_serenet_20231204 (line 142)
                volume(inds) = volume(inds) + (  round(20 + rand()*200) + zeros(size(relativeinds))  );
```
Set limitations and the script works well.

**Comment by kimchange** [comment]
Your modified version is safer, especially in terms of _memory access_. My original way was more considering the _parrallel acceleration_. And I will make an update to make it more memory-safer.
